version: '2'

services:
  huemqtt:
    hostname: eltakomqtt
    image: pharndt/eltakomqtt:${VERSION}
    build: .
    volumes:
      - ./production/config:/var/lib/miele-to-mqtt-gw:ro
    restart: "no"
