version: '2'

services:
    eltakomqtt:
        environment:
            TZ: "Europe/Berlin"
            LOGBACK_XML: /var/lib/miele-to-mqtt-gw/logback.xml
        hostname: eltakomqtt
        image: pharndt/eltakomqtt
        volumes:
            - ./config:/var/lib/eltako-to-mqtt-gw:rw
        restart: always
