version: '2'

services:
    eltakomqtt:
        environment:
            TZ: "Europe/Berlin"
        hostname: eltakomqtt
        image: pharndt/eltakomqtt
        volumes:
            - ./config:/var/lib/eltako-to-mqtt-gw:rw
        restart: always
